/*
 * TransmitSMS.Standard
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using TransmitSMS.Standard.Controllers;
using TransmitSMS.Standard.Http.Client;
using TransmitSMS.Standard.Utilities;

namespace TransmitSMS.Standard
{
    public partial class TransmitSMSClient
    {

        /// <summary>
        /// Singleton access to SMS controller
        /// </summary>
        public SMSController SMS
        {
            get
            {
                return SMSController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Numbers controller
        /// </summary>
        public NumbersController Numbers
        {
            get
            {
                return NumbersController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Lists controller
        /// </summary>
        public ListsController Lists
        {
            get
            {
                return ListsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to EmailSMS controller
        /// </summary>
        public EmailSMSController EmailSMS
        {
            get
            {
                return EmailSMSController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Keywords controller
        /// </summary>
        public KeywordsController Keywords
        {
            get
            {
                return KeywordsController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Resellers controller
        /// </summary>
        public ResellersController Resellers
        {
            get
            {
                return ResellersController.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Account controller
        /// </summary>
        public AccountController Account
        {
            get
            {
                return AccountController.Instance;
            }
        }
        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        #region Constructors
        /// <summary>
        /// Default constructor
        /// </summary>
        public TransmitSMSClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public TransmitSMSClient(string apikey = "APIKEY", string apisecret = "APISECRET")
        {
            Configuration.Apikey = apikey;
            Configuration.Apisecret = apisecret;
        }
        #endregion
    }
}